### ISSUE TITLE
Update to api version 26 possible?

### ISSUE THREAD

**Issue by WorldofShadows** [ReSpeak/rust-ts3plugin#8]
Hey,

first of all thank you for this plugin.
I just wanted to try this, since ts3 is no longer being developed further and there still is no native tts implementation. (and i'm switching to arch from windows on top of that :) )
Would it be possible for you to update this to api 26? The latest plugin only supports 23 and ts3 3.6.2 blocks that sadly right away.

Thank you :)

**Comment by Flakebi** [comment]
Hi, it took a while, but the library is now updated to support api version 26 (and published as version 0.3.0).

FYI, if you didn’t already see it, here’s a plugin I used for tts: https://github.com/ReSpeak/ts3tts (you probably need to adjust the part does the actual tts but it should work otherwise)

**Comment by WorldofShadows** [comment]
Why thank you :) 
Sorry for the late reply, these days are hellish full with work.

ts3tts is actually the plugin that lead me here and It compiled like a charm and is loaded by ts3 now :)

Still have to figure out how to get it to work though, it doesn't output anything atm, despite espeak and alsa present. but that can't be that big of a problem.

Anyway. Ty :D
